# Generated by Django 4.0.6 on 2022-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog_user_qualification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='perce',
            field=models.IntegerField(null=True),
        ),
    ]
